[package]
name = "benches"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tabled = { path = ".." }

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "to_string"
harness = false
